:feat: ✨ Added device preview support
SimformSolutionsPvtLtd/flutter_project_template pull request #13
Opened 2023-08-21 10:06 UTC by Kashifalaliwala

2023-08-22 05:55 UTC, aditya-css requested changes

2023-08-22 05:55 UTC, aditya-css commented on {{cookiecutter.repo_name}}/.idea/runConfigurations/prod.xml
These runConfigurations files are meant to be stored in VCS for the template. It would enable the generated project to have runConfigurations in Android Studio as per flavours. Please do not delete those.

2023-08-22 05:55 UTC, aditya-css commented on {{cookiecutter.repo_name}}/.idea/workspace.xml
Please ensure whether this file is essential or not.

2023-08-22 05:55 UTC, aditya-css commented on {{cookiecutter.repo_name}}/lib/app_config.dart
> +          const {{cookiecutter._app_class_name}}App().withProvider(AppThemeStore()),
Please ensure locale and builder properties in `MaterialApp` are added as per DevicePreview's readme, as I can't see the `app.dart` file being modified in this PR.

2023-08-22 06:15 UTC, Kashifalaliwala commented on {{cookiecutter.repo_name}}/lib/app_config.dart
> +          const {{cookiecutter._app_class_name}}App().withProvider(AppThemeStore()),
Resolved

2023-08-22 06:34 UTC, aditya-css requested changes

2023-08-22 06:34 UTC, aditya-css commented on {{cookiecutter.repo_name}}/lib/app.dart
> +          locale: DevicePreview.locale(context),
I believe this would cause problems if we run any flavor other than device_preview. Can you please confirm and add these properties based on the flavor check?

2023-08-22 06:34 UTC, aditya-css commented on {{cookiecutter.repo_name}}/lib/app.dart
> +import 'package:device_preview/device_preview.dart';
could import as per flavor condition.

2023-08-24 10:10 UTC, aditya-css approved these changes

2023-09-11 06:10 UTC, merged