:sparkles: Refreshed whole project
SimformSolutionsPvtLtd/flutter_project_template pull request #9
Opened 2022-11-18 08:06 UTC by ujas-m-simformsolutions

Update template with below points
*  Fix xcode_backend.sh not found issue
* Add proper Splash screen (add simform logo)
* Network Stream example
* Add Error handling to Repository
* Added flutter_intl for localization
* Add asset gen (flutter_gen)
* Fix IOS orientation not applied natively
* Replace network check function with stream or add separately
* Create all singleton properly for constants and strings
* Create enum for shared prefs keys
* Update SharedPrefs flow
* Create function to create route and pass route settings in it
* Add routes generator to onGenerateRoutes
* Remove unnecessary add provider for helper (already in extensions)
* Add secure storage for tokens
* Remove `^` symbol from packages in pubspec.yaml
* Update flutter version and package version
* Replace AppStrings with Constants and add approutes
* Add navigator key
* Remove getIt
* Rename AppConstants -> Constants
* Add flutterTarget in flavor.gradle

2022-12-21 07:03 UTC, dhvanit-v-simformsolutions commented on {{cookiecutter.repo_name}}/lib/modules/splashScreen/splash_screen.dart
> +  final splashDelay = 3;
If we use this variable at one place we should assign directly and if required we can add comment above the line what is the use case.

2022-12-21 07:13 UTC, dhvanit-v-simformsolutions commented on {{cookiecutter.repo_name}}/lib/routes.dart
> +    Route<dynamic> getRoute({
Make this function private if this is not used outside of scope

2022-12-21 07:18 UTC, dhvanit-v-simformsolutions commented on {{cookiecutter.repo_name}}/lib/services/secure_storage_service.dart
> +import 'package:flutter_secure_storage/flutter_secure_storage.dart';
I guess same file is exists with different name "secure_storage_helper.dart"

2022-12-21 07:19 UTC, dhvanit-v-simformsolutions commented on {{cookiecutter.repo_name}}/lib/services/secure_storage_service.dart
> +import 'package:flutter_secure_storage/flutter_secure_storage.dart';
Remove any of one file

2022-12-21 07:22 UTC, dhvanit-v-simformsolutions commented on {{cookiecutter.repo_name}}/lib/utils/extensions.dart
> +  Widget withProviders(List<Provider<T>> providers) => MultiProvider(
Remove sdp extension or you can refer to regline project as we are not use this anymore. Also add few other extension like isNotNullNotEmpty. 
You can refer regline project for same

2022-12-21 07:24 UTC, dhvanit-v-simformsolutions commented on {{cookiecutter.repo_name}}/lib/apibase/header_interceptor.dart
> +import '../values/enumeration.dart';
I guess we should use package imports instead relative one. Please ask to any other developer for same and change accordingly.

2022-12-21 07:26 UTC, dhvanit-v-simformsolutions requested changes
Please make chages

2022-12-21 08:20 UTC, ujas-m-simformsolutions commented on {{cookiecutter.repo_name}}/lib/routes.dart
> +    Route<dynamic> getRoute({
As this is inside another function linter suggests to not use `_` for this as it scope is already limited.

2022-12-21 08:29 UTC, ujas-m-simformsolutions commented on {{cookiecutter.repo_name}}/lib/apibase/header_interceptor.dart
> +import '../values/enumeration.dart';
The relative imports are recommended by dart team. This is also added in the flutter bible and in official dart docs [here](https://dart.dev/tools/linter-rules#prefer_relative_imports).

2022-12-21 08:47 UTC, dhvanit-v-simformsolutions commented on {{cookiecutter.repo_name}}/lib/services/shared_preferences_service.dart
> +  static SharedPreferencesService get instance => _instance;
Can we directly assign this SharedPreferencesService._() here ?

2022-12-21 08:55 UTC, dhvanit-v-simformsolutions commented on {{cookiecutter.repo_name}}/lib/services/shared_preferences_service.dart
> +  static final SharedPreferencesService _instance =
Referring below comment can we remove this line ?

2022-12-21 08:56 UTC, dhvanit-v-simformsolutions commented on {{cookiecutter.repo_name}}/lib/services/secure_storage_service.dart
> +  static SecureStorageService get instance => _instance;
Can we directly assign this SecureStorageService._() here ?

2022-12-21 08:57 UTC, dhvanit-v-simformsolutions commented on {{cookiecutter.repo_name}}/lib/services/secure_storage_service.dart
> +  static final SecureStorageService _instance = SecureStorageService._();
Referring below comment can we remove this line ?

2022-12-21 08:58 UTC, dhvanit-v-simformsolutions commented on {{cookiecutter.repo_name}}/lib/utils/network_utils.dart
> +  static final NetworkUtils _instance = NetworkUtils._initialise();
^^

2022-12-21 08:59 UTC, dhvanit-v-simformsolutions requested changes
Please make changes

2022-12-21 13:37 UTC, dhvanit-v-simformsolutions approved these changes

2023-08-09 09:49 UTC, vatsaltanna-simformsolutions commented on {{cookiecutter.repo_name}}/lib/app.dart
> +    return Observer(
please make these changes based on the cookie-cutter flag. add a new flag for theme support

2023-08-09 09:49 UTC, vatsaltanna-simformsolutions commented on {{cookiecutter.repo_name}}/lib/app.dart
> +class SimformApp extends StatelessWidget {
change this to the APP name

2023-08-09 09:49 UTC, vatsaltanna-simformsolutions commented on {{cookiecutter.repo_name}}/lib/app_config.dart
>  double devicePixelRatio = 0;
remove this as it is unnecessary.

2023-08-09 09:49 UTC, vatsaltanna-simformsolutions commented on {{cookiecutter.repo_name}}/lib/app_config.dart
> +          child: const SimformApp(),
use extension.

2023-08-09 09:49 UTC, vatsaltanna-simformsolutions commented on {{cookiecutter.repo_name}}/lib/flavors/flavor_config.dart
> +  }) : super(child: child!);
use super.child

2023-08-09 09:49 UTC, vatsaltanna-simformsolutions commented on {{cookiecutter.repo_name}}/lib/main_prod.dart
> +        baseUrl: '{{cookiecutter.base_url}}',
appconstant

2023-08-09 09:49 UTC, vatsaltanna-simformsolutions commented on {{cookiecutter.repo_name}}/lib/modules/splashScreen/splash_screen.dart
> +        height: MediaQuery.of(context).size.height,
use extension

2023-08-09 09:49 UTC, vatsaltanna-simformsolutions commented on {{cookiecutter.repo_name}}/lib/modules/splashScreen/splash_screen.dart
> +class AfterSplash extends StatefulWidget {
please check this

2023-08-21 05:37 UTC, merged